const CarsData = [
  {
    id: 0,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731589108/aaautomartimgs/iqaidxnix8gpj7cxcanx.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes',
    price: '75,000',
    make: 'Mercedes',
    model: 'E-CLASS',
    year: '2022',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Silver',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 1,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731589857/aaautomartimgs/xnm9ljhzkmazdyg2mkyj.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],

    name: 'Cadillac',
    price: '70,000',
    make: 'Cadillac',
    model: 'XT6',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'SUV',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 2,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731589975/aaautomartimgs/i8w6ufsscsn0qjx2y2qq.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Toyota RAV4',
    price: '35,000',
    make: 'Toyota',
    model: 'RAV4',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'SUV',
    extcolor: 'Silver',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 3,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590044/aaautomartimgs/vfw58olzubq7sfmqslsm.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Nissan Rogue',
    price: '22,000',
    make: 'Nissan',
    model: 'Rogue',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'SUV',
    extcolor: 'Orange',
    intcolor: 'Brown',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gaoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 4,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590119/aaautomartimgs/cmejhftesymafr1xcdvx.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Toyota Corolla',
    price: '18,000',
    make: 'Toyota',
    model: 'Corolla',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Blue',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 5,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590202/aaautomartimgs/cly6ry8i31ez7ambrrbs.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Toyota Land Cruiser',
    price: '50,000',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'SUV',
    extcolor: 'White',
    intcolor: 'Black',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 6,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590292/aaautomartimgs/s6ja6ck3mnt2fprvnbbg.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Tesla Model S',
    price: '30,000',
    make: 'Tesla',
    model: 'Model S',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Electric',
    mpg: 'Electric',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 7,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590370/aaautomartimgs/ol8nb5io3wp6zrt34nws.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '50,000',
    make: 'Mercedes',
    model: 'GLC',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'White',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 8,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590486/aaautomartimgs/g8mjaadik1ck2u6wkmou.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '75,000',
    make: 'Mercedes',
    model: 'C-Class Coupe',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coupe',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 9,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590678/aaautomartimgs/uy6ce6halmelrpwf9kwm.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Toyota Corolla',
    price: '24,000',
    make: 'Toyota',
    model: 'Corolla',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Black',
    intcolor: 'Black',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 10,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590796/aaautomartimgs/eekwyo5nhnyiuiv9q6ie.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Nissan Rogue',
    price: '20,000',
    make: 'Nissan',
    model: 'Rogue',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Suv',
    extcolor: 'Orange',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 11,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590862/aaautomartimgs/rrpvsa3sifm9v3df94z4.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'BMW',
    price: '50,000',
    make: 'BMW',
    model: 'M2',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'White',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 12,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590914/aaautomartimgs/mqjzkfldyckzpfocmwav.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '60,000',
    make: 'Mercedes',
    model: 'CLE Cabriolet',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coupe',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 13,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731590989/aaautomartimgs/cvsyoldutd8bbcx5oxad.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'BMW',
    price: '55,000',
    make: 'BMW',
    model: 'M2',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Blue',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 14,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591114/aaautomartimgs/ewxivm7p432uoqoflwcd.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '60,000',
    make: 'Mercedes',
    model: 'C-Class',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coupe',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 15,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591178/aaautomartimgs/pasg6ny0rwi2nnfbzc4n.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '60,000',
    make: 'Mercedes',
    model: 'EQB',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Suv',
    extcolor: 'White',
    intcolor: 'Black',
    transmission: 'Aiutomatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 16,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591248/aaautomartimgs/r6sumjnsqumlxlcg1q0l.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'BMW',
    price: '40,000',
    make: 'BMW',
    model: 'M2',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coupe',
    extcolor: 'Black',
    intcolor: 'Black',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 17,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591295/aaautomartimgs/dpvl6ictcuz1xuzzm6bi.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'HYUNDAI TUCSON',
    price: '25,000',
    make: 'Hyundai',
    model: 'Tucson',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Suv',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 18,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591357/aaautomartimgs/b7fadnasqkkmqmk9ahxy.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Nissan',
    price: '55,000',
    make: 'Nissan',
    model: 'Maxima',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'White',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 19,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591405/aaautomartimgs/svsimvh88udwpgxtirxv.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mercedes-Benz',
    price: '75,000',
    make: 'Mercedes',
    model: 'S-class',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 20,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591457/aaautomartimgs/mkikhhihji2dhbwbtfde.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Toyota RAV4',
    price: '25,000',
    make: 'Toyota',
    model: 'RAV4',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Suv',
    extcolor: 'Silver',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 21,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591527/aaautomartimgs/tjwmcwkzitq96htfjuo6.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Honda',
    price: '25,000',
    make: 'Honda',
    model: 'Civic',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Sedan',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 22,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591615/aaautomartimgs/zswq7hsrynsom2gurxtg.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Mitsubishi',
    price: '22,000',
    make: 'Mitsubishi',
    model: 'Eclipse Cross',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Suv',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 23,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591674/aaautomartimgs/angm23gqp5dlttxtusfy.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Hyundai Tucson',
    price: '20,000',
    make: 'Hyundai',
    model: 'Tucson',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Suv',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 24,
    image: [
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731591756/aaautomartimgs/ild8vcqqnnfqmljlq1vo.png',
      'https://res.cloudinary.com/deiqvcg5b/image/upload/v1731588275/aaautomartimgs/tfo1xtdh1difsoaojl6m.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588682/aaautomartimgs/r28cd2uwicejniabt2nb.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588822/aaautomartimgs/xudxbql9mb63agarvm2f.png',
      'http://res.cloudinary.com/deiqvcg5b/image/upload/v1731588900/aaautomartimgs/adz8dofv4bmoljg58l3z.png',
    ],
    name: 'Nissan Pathfinder',
    price: '32,000',
    make: 'Nissan',
    model: 'Pathfinder',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Suv',
    extcolor: 'Blue',
    intcolor: 'Silver',
    transmission: 'Automatic',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
];

export default CarsData;
